In [1]:
import numpy as np

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# 1. 길이가 10인 0-벡터 만들기

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# 2. 길이가 10이며 다섯번째 원소는 1 나머지는 0인 벡터 만들기

In [10]:
test_vec = np.zeros(10)
test_vec[4] = 1
test_vec

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

# 3. 10 부터 49까지의 값을 가지는 벡터를 만들기

In [14]:
test_vec = np.arange(10, 50)

# 4. 3번 벡터 순서를 바꾸세요.

In [15]:
np.flip(test_vec)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

# 5. 0부터 8까지의 값을 가지는 3x3 행렬 만들기

In [17]:
np.arange(0, 9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 6. 벡터 [1,2,0,0,4,0] 에서 원소의 값이 0이 아닌 원소만 선택한 벡터를 만드세요.


In [33]:
test_vec = np.array([1, 2, 0, 0, 4, 0])
test_vec[test_vec != 0]

array([1, 2, 4])

# 7. 3x3 단위 행렬(identity matrix)을 만드세요


In [35]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 8. 난수 원소를 가지는 3x3 행렬을 만드세요


In [48]:
np.random.seed(0)

test_mat = np.random.rand(3, 3)
test_mat

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276]])

# 9. 위(8번)에서 만든 난수 행렬에서 최대값/최소값 원소를 찾으세요.


In [49]:
np.max(test_mat)

0.9636627605010293

In [50]:
np.min(test_mat)

0.4236547993389047

# 10. 위(8번)에서 만든 난수 행렬에서 행 평균, 열 평균을 계산하세요.


In [52]:
test_mat.mean(axis = 0)

array([0.51042797, 0.67687239, 0.73744008])

In [53]:
test_mat.mean(axis = 1)

array([0.62225542, 0.53814403, 0.76434099])